apiVersion: johnwangwyx.io.io.github.johnwangwyx/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: clusterscan-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  # TODO(user): Add fields here
