apiVersion: johnwangwyx.io.io.github.johnwangwyx/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: clusterscan-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  jobType: ansible
  maxRetry: 3
  schedule: "*/2 * * * *"
  jobParams:
    ENV_VAR1: "ExampleValue1"
    ENV_VAR2: "ExampleValue2"
    ENV_VAR3: "ExampleValue3"
